### ISSUE TITLE
Error while setting date(java.util.Date) field in JdbcRecordWriter 

### ISSUE THREAD

**Issue by anarayn** [j-easy/easy-batch#314]
In my batch job, I am reading data from a CSV file and writing to a database table. I am using FlatFileReader for reading and JdbcRecordWriter for posting the data to tables. In my file, I have a date field in 'dd-MMM-yyyy' (13-JAN-2018) format. To handle the format I've registered a DateTypeConverter with above format in RecordMapper. In my POJO class, I have a java.util.Date field to keep the value. When I try to process my file I get an exception

```
2018-03-31 14:12:06.901 SEVERE [org.easybatch.jdbc.JdbcRecordWriter writeRecords] - Unable to commit transaction
org.postgresql.util.PSQLException: Can't infer the SQL type to use for an instance of java.util.Date. Use setObject() with an explicit Types value to specify the type to use.
at org.postgresql.jdbc2.AbstractJdbc2Statement.setObject(AbstractJdbc2Statement.java:1805)
at org.postgresql.jdbc3g.AbstractJdbc3gStatement.setObject(AbstractJdbc3gStatement.java:37)
at org.postgresql.jdbc4.AbstractJdbc4Statement.setObject(AbstractJdbc4Statement.java:46)
at org.apache.commons.dbcp2.DelegatingPreparedStatement.setObject(DelegatingPreparedStatement.java:188)
at org.apache.commons.dbcp2.DelegatingPreparedStatement.setObject(DelegatingPreparedStatement.java:188)
at org.easybatch.jdbc.BeanPropertiesPreparedStatementProvider.prepareStatement(BeanPropertiesPreparedStatementProvider.java:74)
at org.easybatch.jdbc.JdbcRecordWriter.writeRecords(JdbcRecordWriter.java:81)
at org.easybatch.core.writer.RetryableRecordWriter$RecordWritingCallable.call(RetryableRecordWriter.java:83)
at org.easybatch.core.writer.RetryableRecordWriter$RecordWritingCallable.call(RetryableRecordWriter.java:70)
at org.easybatch.core.retry.RetryTemplate.execute(RetryTemplate.java:66)
at org.easybatch.core.writer.RetryableRecordWriter.writeRecords(RetryableRecordWriter.java:62)
at org.easybatch.core.job.BatchJob.writeBatch(BatchJob.java:235)
at org.easybatch.core.job.BatchJob.call(BatchJob.java:103)
at org.easybatch.core.job.BatchJob.call(BatchJob.java:45)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
```

I feel BeanPropertiesPreparedStatementProvider is not able to map the value to the date field.  To resolve this I changed the type to java.sql.Date in my Pojo and I created a SqlDate Converter. After this, my process is working fine -

```Java
public class SqlDateConverter implements TypeConverter<String,Date>{
	.......
	public SqlDateConverter(String format) {
		this.format=new SimpleDateFormat(format);
	}
	@Override
	public Date convert(String value) {
		// TODO Auto-generated method stub
		java.util.Date parsed;
		try {
			parsed = this.format.parse(value);
			return new Date(parsed.getTime());
	......
	}
}
```

**Comment by benas** [comment]
Hi @anarayn,

Thank you for reporting this issue! I was able to reproduce the case with postgres 12.1 (jdbc driver v42.2.9). However, the same example works fine with H2 and Mysql..

It looks like this is a bug in postgres when mapping a `java.util.Date` to a column: https://www.postgresql.org/message-id/3a69fa320711090848n7d51dc57td54f23e0754679cb@mail.gmail.com but it is old and does not seem to be fixed even in latest release 12.1.

That said, I fixed the issue by calling `preparedStatement.setObject` with an explicit sql type (see 1ae6c60ac0b2b2818f0812e79682b4f683a22ee4). You can try it already in 5.3.0-SNAPSHOT. Please let me know if you still have any issue.
