### ISSUE TITLE
UnivocityCsvRecordMapper java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by seseso** [j-easy/easy-batch#374]
Trying to use UnivocityCsvRecordMapper to read and map a CSV file. It always throws this exception:

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at org.jeasy.batch.extensions.univocity.AbstractUnivocityRecordMapper.processRecord(AbstractUnivocityRecordMapper.java:70)
	at org.jeasy.batch.extensions.univocity.UnivocityCsvRecordMapper.processRecord(UnivocityCsvRecordMapper.java:36)

The Unit test have the same problem (version 6.0.0)

**Comment by seseso** [comment]
I must have a problem on my code as I'm creating a dynamic POJO and with that, the exception occurs.
Sorry for the inconvenience!
